### ISSUE TITLE
UIP-0109 essential desks behaviour

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/UIPs#32]
@philipcmonk how does this handle the case where a non-essential desk signals compatibility but then actually isn't compatible & fails to compile? Would it auto-suspend it or abort the whole upgrade?

sorry if this has been discussed already

**Comment by philipcmonk** [comment]
I think it should auto-suspend in that case

**Comment by tinnus-napbus** [comment]
cool makes sense
