### ISSUE TITLE
UIP-0122: Comments and Questions

### ISSUE THREAD

**Issue by matthew-levan** [urbit/UIPs#49]
Questions and comments on [UIP-0122](https://github.com/urbit/UIPs/blob/main/UIPS/UIP-0122.md):

1. If the inability to delete jet registrations is a memory leak, is not Urbit *itself* a memory leak (since events can't be deleted, at least insofar as their effects are recorded in the snapshot)?
2. "If the `cape` is `|` then any noun matches the `sock`." This is the case for a fresh jet registration to occur, correct?
3. "If the `cape` of a `sock` is a cell but `data` is an atom, then the registration MUST be discarded for an invalid sock." What does this mean? Clarification please.
4. Why do we need to use `~.` only around the "outer entry points" (outer arms of Arvo, `+{load,peek,poke,wish}`)?
5. Is there any concern of performance degradation (either in time or space) from `~.` runes producing increasingly large `wilt`s, and thereby simply translating the "memory leak" from the existing interpreter-side cold state format to the Mars-side Hoon? Perhaps this is ameliorated with interpreter caching?

**Comment by joemfb** [comment]
I don't understand `1.`, as events can clearly be deleted.

The claim that "jet registrations cannot be deleted" is an overstatement. Jet registrations need to be preserved so long as a) you expect to be able to run the jet via that specific registration (core subset) without b) "reintroducing" that core (which would re-register it). That's very hard to know from the runtime with any kind of certainty.

An easier condition to establish is "the battery in this registration is globally unique". In that case it should be fine to delete the registration: no variant of the core is stored elsewhere in the persistent state, so the core will need to be regenerated/reintroduced before it can be run, and that should re-register it.

**Comment by matthew-levan** [comment]
All questions/comments were satisfied by the end of today's Core Architecture meeting. Thank you.

**Comment by matthew-levan** [comment]
All questions/comments were satisfied by the end of today's Core Architecture meeting. Thank you.
